### ISSUE TITLE
Mér finnst að það eigi að vera lag undir

### ISSUE THREAD

**Issue by atliSig** [peturhelgi/peturhelgi.github.io#2] opened 2019-05-27 16:06 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by peturhelgi** [comment] 2019-05-27 16:07
Ég skil.
Duplicate of #1

**Closed as completed by peturhelgi** 2019-05-27 16:07 UTC
